### ISSUE TITLE
Bundle for easy integration with Symfony

### ISSUE THREAD

**Issue by Koc** [asm89/twig-cache-extension#22]
It would be nice add bundle for that. Maybe even no new repository needed (add `Bridge/Symfony` subdirectory)

**Comment by EmanueleMinotto** [comment]
Could this be interesting for you? I'm still working on it, so feedbacks are really welcome. :)
https://github.com/EmanueleMinotto/TwigCacheBundle

imho a bundle should not be included into the library because the library can be used with other frameworks like Laravel or Slim.

**Comment by asm89** [comment]
Use @EmanueleMinotto's twig cache bundle! :)
