### ISSUE TITLE
Allow use variables and expressions as cache key

### ISSUE THREAD

**Issue by Koc** [asm89/twig-cache-extension#26]
Currently only strings are supported
```twig
{% cache cacheKey cacheKeyItems %}
{% endcache %}
```

**Comment by asm89** [comment]
@Koc where do you have problems? It should support expressions [annotation_expression.twig](https://github.com/asm89/twig-cache-extension/blob/1a13fe102241a1b22d2e72a19f31212f328b57a7/test/Asm89/Twig/CacheExtension/Tests/fixtures/annotation_expression.twig).

**Comment by Koc** [comment]
Looks like I'm using outdated version. Will check this

**Comment by asm89** [comment]
Does it work as expected now?

**Comment by Koc** [comment]
Yes, thank you.
