### ISSUE TITLE
Suggestion: Use PSR-6 cache interface

### ISSUE THREAD

**Issue by glen-84** [asm89/twig-cache-extension#31]
Instead of using `CacheProviderInterface`, you could use `Psr\Cache\CacheItemPoolInterface`, which would allow developers to use any PSR-6 compatible caching library.

**Comment by rvanlaak** [comment]
Would be great! Maybe @Nyholm can give some input? Also see https://github.com/EmanueleMinotto/TwigCacheBundle/issues/12

**Comment by asm89** [comment]
Done by @rvanlaak in https://github.com/asm89/twig-cache-extension/pull/32. 🎉
