### ISSUE TITLE
Add support cache tags for PSR6

### ISSUE THREAD

**Issue by Koc** [asm89/twig-cache-extension#36]

**Comment by rvanlaak** [comment]
You can close this issue. See https://github.com/asm89/twig-cache-extension/blob/master/lib/Asm89/Twig/CacheExtension/CacheProvider/PsrCacheAdapter.php

**Comment by Koc** [comment]
No word `tag` inide this class. How to configure tags when saving block?

**Comment by rvanlaak** [comment]
What tags do you mean? Can you please elaborate on your issue because it hasn't a description.

**Comment by Koc** [comment]
https://github.com/symfony/symfony-docs/pull/6947

**Comment by Nyholm** [comment]
We (Symfony and PHP-cache) is going to share an interface for tags that soon will be a PSR. See https://github.com/symfony/symfony/issues/19728

**Comment by asm89** [comment]
Let's re-open an discussion like this once implementations for tagged caching are coming online? The tagging isn't actually part of PSR6, so we'd need implementations for Symfony cache and PHP-Cache specifically in this repository. Not sure what would be the best way of support cache tagging only for those implementation yet, but I'm sure we can figure something out.

**Comment by patie** [comment]
ping

**Comment by Nyholm** [comment]
https://github.com/php-cache/tag-interop

**Comment by Koc** [comment]
@Nyholm do you know when corresponding PSR will be created?

**Comment by Nyholm** [comment]
It is all upp to me. =)

I've talked with Nicholas Grekas, he is using this interface with Symfony. We are also having discussions with Drupal about it and they are satisfied (not officially though) with this interface. 

Im having conversations with @michaelcullum about submitting new PSRs. Im waiting for his green light.

**Comment by patie** [comment]
will be nice to possible add tags for twig blocks, with future invalidation possibility, symfony tagged cache feature - https://symfony.com/blog/new-in-symfony-3-2-tagged-cache
