### ISSUE TITLE
How this suppose to work?

### ISSUE THREAD

**Issue by piernik** [asm89/twig-cache-extension#39]
In php I'm defining `time=time();`
This is my twig code:
```
{% cache 'v1' 10000 %}
    Hello! {{ time }}
{% endcache %}
```

Every time I hit refresh I have new timestamp.
Doesn't it suppose to be fixed for 10 seconds?

**Comment by rvanlaak** [comment]
Well, that depends on your configuration, what cache strategy do you use? Where do you define time? Please elaborate a bit.

**Comment by piernik** [comment]
I though that `10000` is time in miliseconds - is it not?

**Comment by rvanlaak** [comment]
That depends on your configuration, what caching strategy did you configure?

https://github.com/asm89/twig-cache-extension#setup

**Comment by piernik** [comment]
The first one:
```
$cacheProvider = new DoctrineCacheAdapter(new ArrayCache());
$cacheStrategy = new LifetimeCacheStrategy($cacheProvider);
$cacheExtension = new Extension($cacheStrategy);
```

**Comment by asm89** [comment]
@piernik The array cache will not persist across requests. It just caches in an array. That's mainly useful for demo purposes or perhaps if you are re-using the same blocks in one request. If you use doctrine cache make sure to set up a different cache, e.g. apc or memcache.
