### ISSUE TITLE
Mark as abandoned on Packagist and suggest to use twig/cache-extension

### ISSUE THREAD

**Issue by ruudk** [asm89/twig-cache-extension#56]
Is it correct that https://github.com/twigphp/twig-cache-extension is the successor of this repository? If so, please mark this one as abandoned and suggest using the other one.

**Comment by rvanlaak** [comment]
It seems so, given this commit: https://github.com/twigphp/twig-cache-extension/commit/cdea66eccd13d9d20fb745df7d7d7ca7136bd9fa

Probably @asm89 still is in the process of finishing the port (and bringing the extension to 2020).

**Comment by asm89** [comment]
Going forward please use https://github.com/twigphp/twig-cache-extension. I see that @fabpot has set up the new extension correctly. I'll mark this package as deprecated on packagist.org.
